# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['run_api.py'],
    pathex=[],
    binaries=[],
    datas=[('src/cribl_hc', 'cribl_hc')],
    hiddenimports=[
        'cribl_hc',
        'cribl_hc.api',
        'cribl_hc.api.app',
        'cribl_hc.api.routers',
        'cribl_hc.api.routers.analysis',
        'cribl_hc.api.routers.analyzers',
        'cribl_hc.api.routers.credentials',
        'cribl_hc.analyzers',
        'cribl_hc.analyzers.health',
        'cribl_hc.analyzers.config',
        'cribl_hc.analyzers.resource',
        'cribl_hc.core',
        'cribl_hc.core.api_client',
        'cribl_hc.core.orchestrator',
        'cribl_hc.core.health_scorer',
        'cribl_hc.core.report_generator',
        'cribl_hc.models',
        'cribl_hc.utils',
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'pydantic',
        'httpx',
        'typer',
        'rich',
        'structlog',
        'cryptography',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='cribl-hc-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
